---
# Download ceph packages into local APT cache, but not install them.
# Intended to
# - fail early if packages can't be downloaded on some node
# - reduce the time when multiple versions of ceph daemons are running

- name: grab the packages into local cache
  command: >
    apt-get install -y --download-only
    {{ debian_ceph_packages|join(' ') }}
    {{ debian_radosgw_packages|join(' ') }}
  when:
    - not(skip_package_prefetch|default(False)|bool)
    - ceph_package_version.stdout != ceph_candidate_package_version.stdout
