---

- name: get OSD numbers
  shell: >
    find /var/lib/ceph/osd -maxdepth 1 -mindepth 1 -type d
    -name '{{ cluster_name }}-*' -printf '%f\n' |
    sed -e 's/{{ cluster_name }}-//'
  register: osd_ids

- name: disable data rebalancing and scrubbing
  command: ceph osd set {{ item }}
  with_items:
    - noout
    - noscrub
    - "nodeep-scrub"
  delegate_to: "{{ groups.mons[0] }}"

- name: restart OSDs
  include: ./restart_single_osd.yml
  with_items: "{{ osd_ids.stdout_lines }}"

- name: reenable data rebalancing and scrubbing
  command: ceph osd unset {{ item }}
  with_items:
    - noout
    - noscrub
    - "nodeep-scrub"
  delegate_to: "{{ groups.mons[0] }}"

